# Generated by Django 3.1.1 on 2021-06-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210623_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Border')),
                ('description', models.TextField(max_length=600, verbose_name='Description')),
                ('status', models.BooleanField(blank=True, null=True, verbose_name='Active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')),
            ],
            options={
                'verbose_name': 'Border',
                'verbose_name_plural': 'Borders',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='frontier',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_order_status', to='orders.orderstatus', verbose_name='Order Status'),
        ),
        migrations.DeleteModel(
            name='Frontiers',
        ),
        migrations.AddField(
            model_name='order',
            name='border',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_border', to='orders.border', verbose_name='Border'),
            preserve_default=False,
        ),
    ]
