# Generated by Django 3.1.1 on 2021-06-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='certification',
            name='content_es',
            field=models.TextField(null=True, verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_es',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
    ]
