# Generated by Django 3.1.1 on 2021-06-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos', verbose_name=''),
        ),
    ]
